#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BACKEND_DIR="$ROOT_DIR/packages/backend"
TOPIC_NAME="reply-gmail"
SUBSCRIPTION_NAME="reply-gmail-push"

banner "Gmail live sync setup"

stage "Select Google Cloud project"
open_url "https://console.cloud.google.com/home/dashboard"
step "Select the same project that owns MAIL_GOOGLE_CLIENT_ID and has the Gmail API enabled."
ask GOOGLE_CLOUD_PROJECT_ID "Google Cloud project ID:"
ask GOOGLE_CLOUD_PROJECT_NUMBER "Numeric project number:"
ask CONVEX_SITE_URL "Convex site URL (https://...convex.site):"
GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID//[[:space:]]/}
GOOGLE_CLOUD_PROJECT_NUMBER=${GOOGLE_CLOUD_PROJECT_NUMBER//[[:space:]]/}
CONVEX_SITE_URL=${CONVEX_SITE_URL%/}
if [[ ! "$GOOGLE_CLOUD_PROJECT_ID" =~ ^[a-z][a-z0-9-]{4,28}[a-z0-9]$ ]]; then
  warn "Google Cloud project ID is invalid."
  exit 1
fi
if [[ ! "$GOOGLE_CLOUD_PROJECT_NUMBER" =~ ^[0-9]+$ ]]; then
  warn "Google Cloud project number must contain digits only."
  exit 1
fi
if [[ ! "$CONVEX_SITE_URL" =~ ^https://[^/]+\.convex\.site$ ]]; then
  warn "Convex site URL must look like https://deployment.convex.site."
  exit 1
fi
TOPIC_PATH="projects/$GOOGLE_CLOUD_PROJECT_ID/topics/$TOPIC_NAME"
WEBHOOK_URL="$CONVEX_SITE_URL/mail/webhooks/gmail"

stage "Create Pub/Sub topic"
open_url "https://console.cloud.google.com/cloudpubsub/topic/list?project=$GOOGLE_CLOUD_PROJECT_ID"
step "Click Create topic and name it $TOPIC_NAME. Leave the default subscription option off."
step "Open the topic's Permissions panel and grant Pub/Sub Publisher to gmail-api-push@system.gserviceaccount.com."
pause "Continue after the topic and publisher grant are ready."

stage "Create push identity"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=$GOOGLE_CLOUD_PROJECT_ID"
step "Create a service account named reply-gmail-push. It does not need project roles."
step "Open the new service account and copy its email address."
ask MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT "Push service account email:"
MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT=${MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT//[[:space:]]/}
if [[ "$MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT" != *@"$GOOGLE_CLOUD_PROJECT_ID".iam.gserviceaccount.com ]]; then
  warn "The service account email does not belong to the selected project."
  exit 1
fi

stage "Authorize Pub/Sub signing"
PUBSUB_SERVICE_AGENT="service-$GOOGLE_CLOUD_PROJECT_NUMBER@gcp-sa-pubsub.iam.gserviceaccount.com"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=$GOOGLE_CLOUD_PROJECT_ID"
step "Open $MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT, then open its Permissions tab."
step "Grant access to $PUBSUB_SERVICE_AGENT."
step "Assign the Service Account Token Creator role."
note "If subscription creation later reports iam.serviceAccounts.actAs, grant your own account Service Account User on this push identity."
pause "Continue after the role is saved."

stage "Create push subscription"
open_url "https://console.cloud.google.com/cloudpubsub/subscription/list?project=$GOOGLE_CLOUD_PROJECT_ID"
step "Create subscription $SUBSCRIPTION_NAME for topic $TOPIC_NAME and select Push delivery."
step "Set the endpoint URL to $WEBHOOK_URL."
step "Enable authentication and choose $MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT."
step "Set the audience to exactly $WEBHOOK_URL."
pause "Continue after the subscription is created."

stage "Configure Convex"
ask CONVEX_DEPLOYMENT "Convex deployment reference (dev, prod, or deployment name):"
[[ -z "$CONVEX_DEPLOYMENT" ]] && CONVEX_DEPLOYMENT="dev"
say "This sets non-secret identifiers on Convex deployment: $CONVEX_DEPLOYMENT"
say "MAIL_GOOGLE_PUBSUB_TOPIC=$TOPIC_PATH"
say "MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT=$MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT"
if confirm "Write these values to that Convex deployment now?"; then
  (
    cd "$BACKEND_DIR"
    bunx --bun convex env set MAIL_GOOGLE_PUBSUB_TOPIC "$TOPIC_PATH" --deployment "$CONVEX_DEPLOYMENT"
    bunx --bun convex env set MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT "$MAIL_GOOGLE_PUBSUB_SERVICE_ACCOUNT" --deployment "$CONVEX_DEPLOYMENT"
  )
else
  SKIPPED+=("Convex env values for deployment $CONVEX_DEPLOYMENT")
fi

stage "Verify live sync"
say "Deploy or restart the Convex backend so the webhook route and cron jobs are active."
step "Open Reply → Settings → Inboxes. Existing Gmail links are enrolled automatically within 15 minutes."
step "For immediate enrollment, reconnect the Gmail channel once."
step "Confirm the channel displays Live sync on, then send a test email to that Gmail account."
step "The conversation should appear automatically; the 15-minute fallback catches delayed or dropped pushes."
note "Webhook: $WEBHOOK_URL"
note "Topic: $TOPIC_PATH"

finish
